### ISSUE TITLE
Username is not saved - Underlines in username

### ISSUE THREAD

**Issue by epsi1337** [Tkd-Alex/Telegram-InstaPy-Scheduling#34]
Hi, i am using your nice script successful at the moment, but wanted to add my second user account which looks like : user_name_2 - it has two underlines, after saving, it's listed in /users but if i try to execute "/now user_name_2 script" it says: "Sorry username **user** is not saved." (truncates after first underline!)

Can you think of a solution?

Greetings and much respect for your work, 
epsi1337

**Comment by Tkd-Alex** [comment]
It's very strange because my username on instagram is **tkd_alex** and I haven't this issue.
Make you sure to use the right syntax of the command now. 

The user @TarekJ03 have reported and error in readme. The correct syntax of now command is:
/now \<script_name\> \<username\> 

https://github.com/Tkd-Alex/Telegram-InstaPy-Scheduling/pull/30/commits/3abcde9e1dff8bdd5975b73147bed3441788f728#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by epsi1337** [comment]
Uhm after restarting the script and trying again with /now script username it worked..i don't know what i did wrong, maybe i really mixed script and username..but i thought i tried both combinations - ok so anyway, sorry for bothering

greets
